version: '3'
services:
  web:
      restart: always
      build:
          context: ./client
          dockerfile: Dockerfile.dev
      ports:
        - "80:80"
      volumes:
        - /usr/src/app/node_modules
        - ./client:/usr/src/app
  tests:
      build:
          context: ./client
          dockerfile: Dockerfile.dev
      volumes:
        - /usr/src/app/node_modules
        - ./client:/usr/src/app
      command: ["npm", "run", "test"]
  server:
      restart: always
      build:
          context: ./server
          dockerfile: Dockerfile
      ports:
        - "8081:8081"