version: '3'
services:
  web:
      build:
          context: ./client
          dockerfile: Dockerfile.dev
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /usr/src/app/node_modules
        - ./client:/usr/src/app
      environment:
          DEBUG: 'true'
          ENV: 'DEV'
  tests:
      build:
          context: ./client
          dockerfile: Dockerfile.dev
      environment:
          DEBUG: 'false'
          ENV: 'TEST'
      volumes:
        - /usr/src/app/node_modules
        - ./client:/usr/src/app
      command: ["npm", "run", "test"]
  server:
      build:
          context: ./server
          dockerfile: Dockerfile
      environment:
          DEBUG: 'true'
          ENV: 'DEV'
      ports:
        - "8081:8081"